<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRT6VJPQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRT6VJPQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRT6VJPQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRT6VJPQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRT6VJPQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'RT6VJPQ',
    'container.build_id' => '08e184f6',
    'container.build_time' => 1772746972,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRT6VJPQ');
