name: CI

on:
  pull_request:
    branches: [ "dev", "main" ]
  push:
    branches: [ "dev", "main" ]

jobs:
  php:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: perigreen
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: none
          extensions: pdo_mysql, intl, zip

      - name: Validate composer.json
        run: composer validate --no-interaction --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Symfony info
        run: php bin/console about --no-interaction
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/perigreen?serverVersion=8.0.32"

  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check || npx tsc --noEmit

      - name: Lint
        run: npm run lint
